import React from 'react';
import styled from 'styled-components';
import { Button, Row, Col} from 'antd'
import { Parallax } from 'react-parallax';
import { makeStyles } from '@material-ui/core/styles';
import ReactPlayer from 'react-player';

const useStyles = makeStyles(theme => ({
    tailPath: {
        fill: '#fff',
        '-webkit-transform-origin': 'center',
        '-ms-transform-origin': 'center',
        transformOrigin: 'center',
        '-webkit-transform': 'rotateY(0deg)',
        transform: 'rotateY(0deg)',
    },
    titleText: {
        color: 'white',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: '50px',
        fontWeight: 800,
        lineHeight: 1,
        fontSize:'38px',
        fontFamily: 'Montserrat',
        padding: 10,
        textAlign: 'center'

    },
    textContent: {
        color: 'white',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
        marginBottom: '1.75em',
        fontWeight: 400,
        fontSize:'16px',
        fontFamily: 'Montserrat',
        padding: 10,
    },
    radiusRect:{
        borderRadius: '20px !important',
        width: '90% !important',
        boxShadow: '0px 55px 50px -40px #212121',
        '& iframe': {
            borderRadius: '20px !important',
            width: '100% !important',
            zIndex: 10
        }
    }
}));

const IntroSection = () => {

    const classes = useStyles();

    return (
        <div style={{position: 'relative', overflow: 'visible', zIndex: 1}}>
            <S.ParallaxBg bgImage="images/bee-background_1080x1080_8 (1).jpg" bgImageAlt="the cat" strength={500}>
            </S.ParallaxBg>
            <S.Tail>
    			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none" style={{height: '50px', width: '100%'}}>
                	<path className={classes.tailPath} d="M500,97C126.7,96.3,0.8,19.8,0,0v100l1000,0V1C1000,19.4,873.3,97.8,500,97z"></path>
                </svg>
            </S.Tail>
            <S.Container>
                <S.ItemRow justify="center"
                data-aos="fade-right"
                data-aos-delay="300"
                data-aos-duration="1300"
                >
                    <Col xs={24} sm={24} md={24} lg={14} xl={10} className={classes.titleText}>
                        HOW DOES IT WORK?
                    </Col>
                </S.ItemRow>
                <S.ItemRow justify="center"
                data-aos="fade-left"
                data-aos-delay="300"
                data-aos-duration="1300"
                >
                    <Col xs={24} sm={24} md={24} lg={14} xl={10} className={classes.textContent}>
                    The COOLBEEZ DAO treasury, or Community Development Fund (CDF) is used to hold the proceeds from the sale of our NFT collections. The fund is used to purchase and develop land-NFTs on metaverse platforms, such as The SandBox, Decentraland and Somnium Space. All land-NFTs and 100% of the revenue generated by the investments are held in the CDF, as the fund grows so does the value of the NFTs and tokens held by our members.
                    </Col>
                
                </S.ItemRow>
                <S.ItemRow justify="center"
                data-aos="fade-left"
                data-aos-delay="300"
                data-aos-duration="1300"
                >
                    <Col xs={24} sm={24} md={24} lg={14} xl={10} className={classes.textContent}>
                    The investment DAO has been introduced to create trust by utilizing the transparency that the blockchain provides. Our community members will be able to view the value of the CDF and the assets held in addition to being able to see where investments are being made. This means that holders know exactly where their investment is and its value at all times.
                    </Col>
                </S.ItemRow>
                <S.ItemRow justify="center"
                data-aos="fade-right"
                data-aos-delay="300"
                data-aos-duration="1300"
                >
                    <Col xs={24} sm={24} md={24} lg={14} xl={10} className={classes.textContent} style={{marginTop: '2em'}}>
                        <S.ReactPlayer url="https://youtu.be/7WYKFiecFgk" className={classes.radiusRect}></S.ReactPlayer>    
                    </Col>
                </S.ItemRow>
            </S.Container>
            
        
        </div>
        
            
    );
}

const S = {
    Container: styled(Row)`
        height: fit-content;
        width: 100%;
        transform: translateY(8rem);
        overflow: visible;
        
        @media (max-width: 1024px) {
            transform: translateY(4rem);
          }
    `,
    ParallaxBg: styled(Parallax)`
        position: absolute !important;
        height: 100%;
        width: 100%;
        top: 0;

        img {
            @media (max-width: 1024px) {
                height: 100% !important;
              }
        }
       
    `,
    Tail: styled.div`
        overflow: hidden;
        position: absolute;
        left: 0;
        width: 100%;
        line-height: 0;
        direction: ltr;
        bottom: -1px;
    `,
    ItemRow: styled(Row)`
        width: 100%;
    `,
    ReactPlayer: styled(ReactPlayer)`
        width: 100%;
        border-radius: 16px;
    `,
}

export default IntroSection;